import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#060d18',
        'surface-container-low': '#09131f',
        'surface-container': '#132030',
        'surface-container-high': '#1e3a52',
        'surface-container-highest': '#233f57',
        'surface-bright': '#305373',
        'surface-variant': '#1e3a52',
        'surface': '#09131f',
        'background': '#060d18',
        'primary': '#2a9d8f',
        'primary-container': '#187b6e',
        'primary-fixed': '#5cc7b9',
        'primary-fixed-dim': '#2a9d8f',
        'on-primary': '#002824',
        'on-primary-container': '#00423a',
        'on-primary-fixed': '#001a17',
        'on-primary-fixed-variant': '#004c44',
        'secondary': '#b7c8e1',
        'secondary-container': '#3a4a5f',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary': '#213145',
        'on-secondary-container': '#a9bad3',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary': '#e9c46a',
        'tertiary-container': '#c79d38',
        'tertiary-fixed': '#fae3a5',
        'tertiary-fixed-dim': '#e9c46a',
        'on-tertiary': '#4a3b0f',
        'on-tertiary-container': '#6b5820',
        'on-tertiary-fixed': '#2e2304',
        'on-tertiary-fixed-variant': '#857030',
        'error': '#e76f51',
        'error-container': '#ba4326',
        'on-error': '#601908',
        'on-error-container': '#fed2c7',
        'on-surface': '#e8f4f8',
        'on-surface-variant': '#a8c8e8',
        'on-background': '#e8f4f8',
        'outline': '#1e3a52',
        'outline-variant': '#132030',
        'inverse-surface': '#e8f4f8',
        'inverse-on-surface': '#09131f',
        'inverse-primary': '#187b6e',
        'surface-tint': '#2a9d8f',
        
        // Legacy colors (keep for gradual migration)
        'bg-primary': '#060d18',
        'bg-alt': '#09131f',
        'bg-content': '#09131f',
        'bg-card-alt': '#060d18',
        'text-primary': '#e8f4f8',
        'text-secondary': '#a8c8e8',
        'text-tertiary': '#6b8aad',
        'border-primary': '#1e3a52',
        'border-alt': '#132030',
        'accent-blue': '#457b9d',
        'tier-red': '#e76f51',
        'tier-amber': '#e9c46a',
        'tier-green': '#2a9d8f',
        // Owner type colors
        'owner-individual': '#2a9d8f',
        'owner-corporate': '#e9c46a',
        'owner-bank': '#457b9d',
        'owner-foundation': '#d4a574',
        'owner-government': '#c55a7e',
        'owner-otherbanks': '#8491a3',
        'owner-other': '#666666',
      },
      fontFamily: {
        headline: ['var(--font-dm-sans)', 'sans-serif'],
        body: ['var(--font-dm-sans)', 'sans-serif'],
        label: ['var(--font-dm-mono)', 'monospace'],
        // Legacy fonts
        sans: ['var(--font-dm-sans)', 'sans-serif'],
        mono: ['var(--font-dm-mono)', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        full: '100%',
      },
      fontSize: {
        // Responsive font sizes using clamp
        xs: 'clamp(0.75rem, 2vw, 0.875rem)',
        sm: 'clamp(0.875rem, 2.5vw, 1rem)',
        base: 'clamp(0.875rem, 3vw, 1rem)',
        lg: 'clamp(1rem, 4vw, 1.125rem)',
        xl: 'clamp(1.125rem, 5vw, 1.25rem)',
        '2xl': 'clamp(1.375rem, 6vw, 1.5rem)',
        '3xl': 'clamp(1.75rem, 7vw, 2rem)',
      },
      gridTemplateColumns: {
        'auto-fit': 'repeat(auto-fit, minmax(150px, 1fr))',
        'auto-fill': 'repeat(auto-fill, minmax(200px, 1fr))',
      },
      boxShadow: {
        'terminal': '0 20px 40px rgba(0, 0, 0, 0.4)',
        'glow': '0 0 20px rgba(78, 222, 163, 0.3)',
      },
      animation: {
        'marquee': 'marquee 30s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
